name: cult_app
description: "theater"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.0+11

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_phoenix:
  auto_route:
  flutter_bloc:
  http: ^1.2.1
  dio:
  get_it: ^7.6.4
  progress_loader_overlay: ^3.0.3
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_pretty_dio_logger: ^3.0.0
  hive_flutter: ^1.1.0
  form_field_validator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_styled_toast: ^2.2.1
  basic_utils: ^5.7.0
  collection: ^1.18.0
  infinite_scroll_pagination: ^4.0.0
  webview_flutter: ^4.7.0
  flutter_dash: ^1.0.0
  qr_flutter: ^4.1.0
  onesignal_flutter: ^5.1.3
  flutter_launcher_icons: ^0.13.1
  firebase_analytics:
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  launcher_name: ^1.0.2
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^11.3.0

  
  
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"



launcher_name:
  default: "Театр Культ"
  en: "Cult Theatre"
  uk: "Театр Культ"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

 